### ISSUE TITLE
Better Error Message for Exceed Token Limits

### ISSUE THREAD

**Issue by owenzhao** [DanielEdrisian/AlexSideBar-Public#23]
**Describe the feature**
When I send a big json file (2.5 MB) to Alex, it reply that error connected with LLM. However, the real issue is that the tokens it needs exceed the limit of the max token size. So it is better to say it directly as the connection has no issue at all.

**Screenshots/Screen recordings**
none

**What version are you on currently?**
 - Version [e.g. 1.2.0]

**Comment by DanielEdrisian** [comment]
Definitely will fix

**Comment by owenzhao** [comment]
When token limitation exceeded, all prompts after it will be unusable. That
is because the file to be blamed on this is in the context. I have to use
cmd+N to create another new window of Alex. You should tell this on the
error message as well

Daniel Edrisian ***@***.***> 于 2024年11月24日周日 下午11:27写道：

**Comment by DanielEdrisian** [comment]
Hey! New version out which should fix the error message, and now it's optimized so it should happen less often. Lmk if it works better for you.

**Comment by owenzhao** [comment]
> Hey! New version out which should fix the error message, and now it's optimized so it should happen less often. Lmk if it works better for you.

Where is the new version? I can't find it. The latest version on the site was still the 1.2.0(66).

**Comment by DanielEdrisian** [comment]
Had to pull it back cause there was a crash happening, will send it out again tonight

**Comment by DanielEdrisian** [comment]
Hey, can you try the latest version?

**Comment by owenzhao** [comment]
v1.3.5 

An 8.5 MB json file.

<img width="1331" alt="截屏2024-12-11 11 42 21" src="https://github.com/user-attachments/assets/3accfac0-7e1c-4a66-ac2a-df107d5dfb8b">

**Comment by DanielEdrisian** [comment]
8.5Mb is above the limit. That's about 8.5 million characters (or ~2M tokens)

**Comment by owenzhao** [comment]
> 8.5Mb is above the limit. That's about 8.5 million characters (or ~2M tokens)

True. I just want to test the new error message.

**Comment by DanielEdrisian** [comment]
Awesome! Glad it works finally lol
