### ISSUE TITLE
Keyboard shortcut to change between models

### ISSUE THREAD

**Issue by rudrankriyam** [DanielEdrisian/AlexSideBar-Public#34]
**Describe the feature**
There can be a nice keyboard shortcut to switch between models, like `Command + /' and 'Command + .'

Something like: 

`Option` + `Command` + `/`, and then use the `up` and `down` arrow keys to change the model.

**What version are you on currently?**
 - Version 1.3.5

**Comment by DanielEdrisian** [comment]
We currently have cmd+/, but I like the option+cmd+/ up/down idea

**Comment by rudrankriyam** [comment]
cmd+/ is good enough
