### ISSUE TITLE
Create new chat button keeps the first chat view.

### ISSUE THREAD

**Issue by owenzhao** [DanielEdrisian/AlexSideBar-Public#35]
**Describe the bug**
After clicking the new chat button, the first chat view is still there.

**Screenshots/Screen recordings**

https://github.com/user-attachments/assets/1b6b0b91-e41b-4a41-9f74-76330ee59192

**What version are you on currently?**
 - Version 1.3.5 (79)

**Comment by DanielEdrisian** [comment]
Yep, also annoys me. Will prioritize this for tomorrow.

**Comment by DanielEdrisian** [comment]
@owenzhao This is now fixed in the latest version (1.3.7). let me know if it works for you!

**Comment by owenzhao** [comment]
It works.

**Comment by owenzhao** [comment]
A new issue may introduced by this fix. https://github.com/DanielEdrisian/AlexSideBar-Public/issues/45
