### ISSUE TITLE
Alex Answers Return Key from Input Method when the Prompts are Not Finished.

### ISSUE THREAD

**Issue by owenzhao** [DanielEdrisian/AlexSideBar-Public#4]
**Describe the bug**
For people in Asia using input method like Pinyin, the Return key is to output Pinyin as English. However, Alex will get that Return key passed by the input method and start to answer the question. The question is not finished. Alex should ignore that key and only answer the return directly send to it.

**Screenshots/Screen recordings**
https://x.com/DanielEdrisian/status/1857982838781747605

**What version are you on currently?**
 - Version 1.2.0 (66)

**Comment by DanielEdrisian** [comment]
Hey! Finally got around to fixing this, lmk if it works for you now! Released in today's update (1.3.17)
