### ISSUE TITLE
Alex will randomly display extra input views.

### ISSUE THREAD

**Issue by owenzhao** [DanielEdrisian/AlexSideBar-Public#45]
**Describe the bug**
As shown in the figure, there are two input views, but the one above is blank. I haven't found much of a pattern, but sometimes it appears out of the blue. However, its occurrence seems to be higher after using the "New Chat" button. 

> It's not necessarily two, and sometimes there could be more. I suspect it might be related to the frequency from the previous round of conversation.

**Screenshots/Screen recordings**

<img width="885" alt="截屏2024-12-13 19 08 59" src="https://github.com/user-attachments/assets/e8de8c4a-c578-438e-863d-050a634c6281" />

**What version are you on currently?**
 - Version 1.3.7 (81)

**Comment by DanielEdrisian** [comment]
This has been fixed
