### ISSUE TITLE
Clicking the Apply Button Hangs

### ISSUE THREAD

**Issue by Carlos028** [DanielEdrisian/AlexSideBar-Public#46]
**Describe the bug**
When I click the apply button, nothing happens but Xcode is brought to the front. 

**Screenshots/Screen recordings**
Recording attached. 

**What version are you on currently?**
 - Version 1.3.8

https://github.com/user-attachments/assets/b6a5981a-1c9a-4f28-aa26-57ebb6219e70

**Comment by DanielEdrisian** [comment]
Can you try with the latest version (1.3.12) and see if it's still happening?

**Comment by rudrankriyam** [comment]
Can you try with the latest version (1.3.14) where we re-did the **apply** implementation and see if it is still happening? @Carlos028
