### ISSUE TITLE
Alex‘s Apply didn't switch to the correct file in Xcode

### ISSUE THREAD

**Issue by owenzhao** [DanielEdrisian/AlexSideBar-Public#59]
**Describe the bug**
When two files need to be revised, Alex didn't switch to the correct file. Alex applied all changes to the current tab unless I switch to the correct tab manually.

**What version are you on currently?**
 - Version 1.3.15 (96)

**Comment by owenzhao** [comment]
> Besides that, does the apply experinece seem better? Any speed issues or apply not showing up?

The new approach is really fast most of the time. Rarely, it may not apply as it should and need to apply again. I just got once that it didn't show the apply immediately, which fall through like the old apply way. After all, this is a great upgrade.

**Comment by DanielEdrisian** [comment]
Just fixed this in the latest update! (1.3.16)
