### ISSUE TITLE
Add File button leads to Xcode build errors.

### ISSUE THREAD

**Issue by owenzhao** [DanielEdrisian/AlexSideBar-Public#63]
**Describe the bug**
Add file from Alex leads Xcode build errors.

**Screenshots/Screen recordings**
<img width="759" alt="截屏2024-12-23 11 23 37" src="https://github.com/user-attachments/assets/c5866c14-7c9f-4ca8-ab18-404cb77c9eea" />

<img width="1909" alt="截屏2024-12-23 11 25 40" src="https://github.com/user-attachments/assets/211b700a-878d-48d6-a2de-9c93f53ccbb9" />

<img width="1052" alt="截屏2024-12-23 11 26 17" src="https://github.com/user-attachments/assets/70dda634-f39d-4228-9e7d-e2c3557ef6b9" />

**What version are you on currently?**
 - Version 1.3.16 (97)

**Comment by DanielEdrisian** [comment]
Ok, i've identified the issue

**Comment by DanielEdrisian** [comment]
Fixed the issue in 1.3.17
