### ISSUE TITLE
Prompt input becomes unresponsive when accessing add-context submenu

### ISSUE THREAD

**Issue by romanr** [DanielEdrisian/AlexSideBar-Public#8]
Prompt input becomes unresponsive sooner or later, could be half day or an hour. USually it's beachball when you select Code or files in sub-menu.
Here it beachballs but recovers. Usually it's beachball and only Force Quit.

Version 1.2.0

https://github.com/user-attachments/assets/012f8505-6d85-4988-9c9f-8de9e9c70111

**Comment by DanielEdrisian** [comment]
Hey! Just fixed this in the new version (1.3.0). Lmk if you still encounter it.
