### ISSUE TITLE
URGENT: Multilingual input is not usable in version 2.1.

### ISSUE THREAD

**Issue by owenzhao** [DanielEdrisian/AlexSideBar-Public#80]
**Describe the bug**
In the video, when using multilingual input, Alex exhibits a phenomenon of missing characters. I think this might be related to the label names generated above.

**Screenshots/Screen recordings**

https://github.com/user-attachments/assets/781d0394-122d-4ebe-b241-30fd30531d38

**What version are you on currently?**
 - Version 2.1.0 (102)

**Comment by owenzhao** [comment]
I have temporarily reverted to version 2.0.

**Comment by DanielEdrisian** [comment]
Oh interesting, this is due to the auto saving that's happening. Let me check it out

**Comment by DanielEdrisian** [comment]
Ok I've identified the issue. Working on a fix.

**Comment by DanielEdrisian** [comment]
Just pushed a new version (2.1.2) with the fix. Lmk if it works!

**Comment by owenzhao** [comment]
It works. Thank you very much for the quick fix!
